import type { CodeTables, JewelryItem } from '../types/inventory';

export const DEFAULT_CODE_TABLES: CodeTables = {
  types: [
    { code: 'PD', label: 'Pendant Set', description: 'Pendant with matching earrings' },
    { code: 'NLS', label: 'Necklace Set', description: 'Full necklace with earrings & maangtikka' },
    { code: 'EAR', label: 'Earrings / Jhumkas', description: 'Drop earrings, studs, chandbalis, jhumkas' },
    { code: 'CHK', label: 'Choker Set', description: 'Collar / high-neck choker with studs' },
    { code: 'BNG', label: 'Bangles / Kadas', description: 'Openable kadas, traditional bangle sets' },
    { code: 'BRC', label: 'Bracelet', description: 'Tennis bracelets, charm cuffs' },
    { code: 'RNG', label: 'Finger Ring', description: 'Adjustable statement & solitaire rings' },
    { code: 'MNG', label: 'Mangalsutra', description: 'Contemporary & traditional black bead chains' },
    { code: 'OTH', label: 'Other Accessories', description: 'Brooches, hair ornaments, nose rings' },
  ],
  stones: [
    { code: 'D', label: 'American Diamond (CZ)', description: 'High-clarity cubic zirconia simulants' },
    { code: 'K', label: 'Kundan', description: 'Traditional foil-backed glass stones' },
    { code: 'PK', label: 'Polki', description: 'Uncut diamond look in jadau setting' },
    { code: 'P', label: 'Cultured Pearl / Moti', description: 'Freshwater imitation pearl drops' },
    { code: 'J', label: 'Jade / Semi-precious Bead', description: 'Carved jadeite & dyed quartz drops' },
    { code: 'E', label: 'Emerald Simulant', description: 'Deep forest green hydro stones' },
    { code: 'R', label: 'Ruby Simulant', description: 'Pigeon blood synthetic corundum' },
    { code: 'TX', label: 'Meenakari / Temple', description: 'Enamel painted & carved antique work' },
    { code: 'NO', label: 'Plain Metal / No Stone', description: 'Pure metal finish with no encrusting' },
  ],
  colors: [
    { code: '01', label: 'Antique Gold Tone', description: 'Warm matte 22K finish brass' },
    { code: '02', label: 'Silver / Rhodium Tone', description: 'Bright white rhodium plating' },
    { code: '03', label: 'Rose Gold Tone', description: 'Modern pink copper hue' },
    { code: '12', label: 'Emerald Green', description: 'Rich deep royal green' },
    { code: '15', label: 'Ruby Maroon', description: 'Traditional wedding deep red' },
    { code: '20', label: 'Mint / Sage Green', description: 'Pastel bridal tone' },
    { code: '30', label: 'Royal Blue / Sapphire', description: 'Navy and cobolt faceted highlights' },
    { code: '40', label: 'Baby Pink / Rose Quartz', description: 'Soft powder pink highlights' },
    { code: '99', label: 'Multicolour / Navratna', description: 'Multi-stone composite palette' },
  ],
};

export const INITIAL_INVENTORY: JewelryItem[] = [
  {
    id: 'item-1',
    sku: 'PDJ12001',
    title: 'Emerald Green Floral Pendant Set',
    typeCode: 'PD',
    stoneCode: 'J',
    colorCode: '12',
    serial: '001',
    buyingPrice: 450,
    sellingPrice: 1250,
    quantity: 14,
    reorderLevel: 5,
    vendor: 'Aura Creations Jaipur',
    notes: 'Micro-plated brass with drop hydro jade beads and matching studs.',
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80',
    dateAdded: '2026-08-15',
  },
  {
    id: 'item-2',
    sku: 'NLSK15001',
    title: 'Heritage Kundan Choker Necklace Set',
    typeCode: 'NLS',
    stoneCode: 'K',
    colorCode: '15',
    serial: '001',
    buyingPrice: 1600,
    sellingPrice: 4200,
    quantity: 6,
    reorderLevel: 3,
    vendor: 'Royal Zari Crafts',
    notes: 'Handcrafted kundan with cluster maroon glass pearls and dori tassel.',
    imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&auto=format&fit=crop&q=80',
    dateAdded: '2026-08-20',
  },
  {
    id: 'item-3',
    sku: 'EARD01001',
    title: 'Solitaire Halo CZ Drop Earrings',
    typeCode: 'EAR',
    stoneCode: 'D',
    colorCode: '01',
    serial: '001',
    buyingPrice: 320,
    sellingPrice: 890,
    quantity: 2,
    reorderLevel: 4, // Below reorder level!
    vendor: 'ShineStar Imports',
    notes: 'AAA Swiss cubic zirconia with hypoallergenic push-back studs.',
    imageUrl: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&auto=format&fit=crop&q=80',
    dateAdded: '2026-08-22',
  },
  {
    id: 'item-4',
    sku: 'BNGPK01001',
    title: 'Antique Openable Polki Kada Pair',
    typeCode: 'BNG',
    stoneCode: 'PK',
    colorCode: '01',
    serial: '001',
    buyingPrice: 1100,
    sellingPrice: 2800,
    quantity: 8,
    reorderLevel: 3,
    vendor: 'Aura Creations Jaipur',
    notes: 'Screw hinge lock, fits size 2.4 to 2.8 comfortably.',
    imageUrl: 'https://images.unsplash.com/photo-1611591475155-42e9fba5ce55?w=600&auto=format&fit=crop&q=80',
    dateAdded: '2026-08-25',
  },
  {
    id: 'item-5',
    sku: 'RNGD02001',
    title: 'Baguette Eternity Adjustable Ring',
    typeCode: 'RNG',
    stoneCode: 'D',
    colorCode: '02',
    serial: '001',
    buyingPrice: 180,
    sellingPrice: 650,
    quantity: 1,
    reorderLevel: 5, // Below reorder level!
    vendor: 'ShineStar Imports',
    notes: 'Rhodium coated brass, premium prong setting.',
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80',
    dateAdded: '2026-08-28',
  },
  {
    id: 'item-6',
    sku: 'CHKP99001',
    title: 'Navratna Multi-Hue Pearl Choker',
    typeCode: 'CHK',
    stoneCode: 'P',
    colorCode: '99',
    serial: '001',
    buyingPrice: 850,
    sellingPrice: 2150,
    quantity: 0, // Out of stock!
    reorderLevel: 3,
    vendor: 'Royal Zari Crafts',
    notes: 'Multi-color beads layered with faux pearls, adjustable thread tie.',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80',
    dateAdded: '2026-08-29',
  }
];
